name: shiny_app_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.19
  - pandas
  - shiny
  - pygwalker
  - requests
  - langchain
  - aiohttp  # For async operations
  - nodejs  # Required for some LangChain dependencies
  - pip
  - pip:
      - ollama  # If not available via conda, install via pip
